version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: web
    command: ["./entrypoint.sh"]
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

volumes:
  db_data:
    name: db_data
