"""empty message

Revision ID: b279dd2dc827
Revises: 
Create Date: 2023-10-14 21:09:13.452878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b279dd2dc827'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trivia_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('insertion_order', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trivia_questions_id'), 'trivia_questions', ['id'], unique=False)
    op.create_index(op.f('ix_trivia_questions_question'), 'trivia_questions', ['question'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trivia_questions_question'), table_name='trivia_questions')
    op.drop_index(op.f('ix_trivia_questions_id'), table_name='trivia_questions')
    op.drop_table('trivia_questions')
    # ### end Alembic commands ###
